blank_issues_enabled: true
contact_links:
  - name: Contributing Guide
    url: https://github.com/bryanegan/dndblog/blob/main/CONTRIBUTING.md
    about: Read our guide for submitting blog posts and code contributions
